In [1]:
import sys,os
import pandas as pd

module_path = os.path.abspath(os.path.join('..'))
if module_path not in sys.path:
    sys.path.append(module_path)
from wgpack.cdip import get_CDIP_wavesbulk

In [2]:
ta = pd.to_datetime('2022-02-14 06:00:00')
tb = pd.to_datetime('2022-03-14 06:00:00')
stn = '100'

Cdf = get_CDIP_wavesbulk(stn, startdate=ta, enddate=tb)
Cdf

                     Hsig         Tp         Ta         Dp
Date
2022-02-14 06:00:00  0.77  14.285714   9.994115  205.06250
2022-02-14 06:30:00  0.74  12.500000   9.700722  216.31250
2022-02-14 07:00:00  0.84  12.500000  10.343173  230.37500
2022-02-14 07:30:00  0.73  13.333333   9.766189  216.31250
2022-02-14 08:00:00  0.78  13.333333  10.287261  220.53125
...                   ...        ...        ...        ...
2022-03-14 04:00:00  0.87  16.666668   6.414755  219.12500
2022-03-14 04:30:00  0.84  16.666668   6.465721  221.93750
2022-03-14 05:00:00  0.91  14.285714   6.286774  202.25000
2022-03-14 05:30:00  0.91  16.666668   6.496899  219.12500
2022-03-14 06:00:00  0.94  16.666668   6.199517  213.50000

[1345 rows x 4 columns]